### ISSUE TITLE
[BUG] when you save the map the IO connections are lost

### ISSUE THREAD

**Issue by Atope89** [Adsito/RustMapEditor#30]
After editing a map and saving it, the IO connections of the custom monuments are lost. 
Test in the master and beta branch with windows 10 and Unity 2021.1.16f1.
Thank you very much for the work it is a great project.

**Comment by Adsito** [comment]
Thanks for the report, unfortunately that is the intended behaviour. 
IO connections are a 3rd party extension to a map file, therefore are not supported by this open sourced project.

This is also the reason the Editor can open "password protected" map files.
